services:
  # build and run the local image instead
  # note: it's currently expose on port 3008
  jore4-hastus:
    build:
      context: ".."
      network: host
    ports:
      - "127.0.0.1:3008:8080"
    networks:
      - jore4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SECRET_STORE_BASE_PATH: "/mnt/secrets-store"

  jore4-testdb:
    extends:
      file: docker-compose.base.yml
      service: jore4-testdb-base
    container_name: "testdb"
    ports:
      - "127.0.0.1:6432:5432"

  jore4-hasura:
    container_name: "hasura"
    ports:
      - "127.0.0.1:3201:8080"
    # Waiting for database to be ready to avoid startup delay due to hasura crashing at startup if db is offline
    # Note: this should only be done in development setups as Kubernetes does not allow waiting for services to be ready
    depends_on:
      jore4-testdb:
        condition: service_healthy
