---
version: "3.8"
services:
  # build and run the local image instead
  # note: it's currently expose on port 3008
  jore4-hastus:
    container_name: "hastus-processor"
    build:
      context: ".."

  jore4-testdb-test:
    container_name: "database-test"
    extends:
      service: jore4-testdb-base
      file: docker-compose.base.yml
    image: "${TESTDB_DOCKER_IMAGE}"
    ports:
      - "127.0.0.1:6433:5432"

  jore4-tiamat-test:
    container_name: "tiamat-test"
    extends:
      service: jore4-tiamat-base
      file: docker-compose.base.yml
    image: "${TIAMAT_DOCKER_IMAGE}"
    environment:
      - TIAMAT_DB_URL=jdbc:postgresql://jore4-testdb-test:5432/stopdb?stringtype=unspecified
    depends_on:
      jore4-testdb-test:
        condition: service_healthy

  jore4-hasura-test:
    container_name: "hasura-test"
    image: "${HASURA_DOCKER_IMAGE}"
    extends:
      service: jore4-hasura-base
      file: docker-compose.base.yml
    ports:
      - "127.0.0.1:3202:8080"
    depends_on:
      jore4-testdb-test:
        condition: service_healthy
      jore4-tiamat-test:
        condition: service_healthy
    environment:
      - DB_HOSTNAME=jore4-testdb-test
      - SKIP_SET_VARIABLE_SECRET_OVERRIDE=true
      - TIAMAT_HOSTNAME=jore4-tiamat-test
      - TIMETABLESAPI_HOSTNAME=jore4-timetablesapi
