---
version: "3.8"
services:
  # build and run the local image instead
  # note: it's currently expose on port 3008
  jore4-hastus:
    build:
      context: ".."

  jore4-hasura:
    # locking hasura image so that we can develop against a static graphql API
    # Link to available jore4-hasura images in Docker Hub:
    # https://hub.docker.com/r/hsldevcom/jore4-hasura/tags?page=1&ordering=last_updated
    # The :seed tag contains the latest main-build image with seed data.
    image: 'hsldevcom/jore4-hasura:seed-main--20230315-e9a40861ebd8bb78d777ce18c7a942c5cbdbfd74'
    # Waiting for database to be ready to avoid startup delay due to hasura crashing at startup if db is offline
    # Note: this should only be done in development setups as Kubernetes does not allow waiting for services to be ready
    depends_on:
      jore4-testdb:
        condition: service_healthy
